server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # jdbc:mysql://localhost:3306/db_lemon?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true
    url: jdbc:mysql://localhost:3306/db_lemon?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: 123456
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/config/mybatis-config.xml
    